### ISSUE TITLE
Cannot install triggers on tables which do not have a primary key

### ISSUE THREAD

**Issue by kevin-cantwell** [pagarme/teleport#11]
If the source schema contains tables without a primary key, installing triggers logs this error and panics:

```
source_1 | 2016/05/26 18:26:24 Error installing triggers on table table_name: table table_name does not have primary key!
source_1 | panic: runtime error: invalid memory address or nil pointer dereference
source_1 | [signal 0xb code=0x1 addr=0x0 pc=0x4963ff]
source_1 |
source_1 | goroutine 1 [running]:
source_1 | github.com/pagarme/teleport/database.(*Table).Diff(0xc8200f0540, 0x0, 0x0, 0xc820015cd0, 0x6, 0x0, 0x0, 0x0)
source_1 | 	/go/src/github.com/pagarme/teleport/database/table.go:95 +0x5bf
source_1 | github.com/pagarme/teleport/batcher/ddldiff.Diff(0xaf7680, 0x0, 0x0, 0xc8204a8000, 0x2aa, 0x400, 0xc820015cd0, 0x6, 0x0, 0x0, ...)
source_1 | 	/go/src/github.com/pagarme/teleport/batcher/ddldiff/ddldiff.go:22 +0x240
source_1 | github.com/pagarme/teleport/batcher/ddldiff.Diff(0xaf7680, 0x0, 0x0, 0xc82049d620, 0x1, 0x1, 0xc820015cd0, 0x6, 0x0, 0x0, ...)
source_1 | 	/go/src/github.com/pagarme/teleport/batcher/ddldiff/ddldiff.go:27 +0xaeb
source_1 | github.com/pagarme/teleport/database.(*Ddl).Diff(0xc8201139f0, 0x0, 0x0, 0x0)
source_1 | 	/go/src/github.com/pagarme/teleport/database/ddl.go:63 +0x1f6
source_1 | github.com/pagarme/teleport/loader.(*Loader).createDDLBatch(0xc820113d30, 0x0, 0x0, 0x0, 0x0, 0x0)
source_1 | 	/go/src/github.com/pagarme/teleport/loader/ddl.go:27 +0x297
source_1 | github.com/pagarme/teleport/loader.(*Loader).Load(0xc820113d30, 0x0, 0x0)
source_1 | 	/go/src/github.com/pagarme/teleport/loader/loader.go:46 +0x10a
source_1 | main.main()
source_1 | 	/go/src/github.com/pagarme/teleport/main.go:112 +0x1331
```

**Comment by pedrofranceschi** [comment]
Hi Kevin,

Teleport does not support replicating tables without primary key, as it is
not possible to ensure consistency on DML updates.

Could you try adding a primary key and checking if it works?

**Comment by kevin-cantwell** [comment]
Makes sense. I think a little note in the readme might be helpful there :)
